apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      tier: frontend
      app: nginx
  # this is pod definition
  template:
    metadata:
      # these labels belongs to pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port


    this is a not a partial claim this is a pre and post claims 
    wipro@vidalhealth.com